set_property PACKAGE_PIN AG17 [get_ports acq_gate_out_0]
set_property PACKAGE_PIN AB12 [get_ports acq_trig_out_0]
set_property PACKAGE_PIN AC14 [get_ports eom_out_0]
set_property PACKAGE_PIN AD16 [get_ports soa_gate_out_0]
set_property IOSTANDARD LVCMOS33 [get_ports acq_gate_out_0]
set_property IOSTANDARD LVCMOS33 [get_ports acq_trig_out_0]
set_property IOSTANDARD LVCMOS33 [get_ports eom_out_0]
set_property IOSTANDARD LVCMOS33 [get_ports soa_gate_out_0]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_1_0_io0_io]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_1_0_io1_io]
set_property PACKAGE_PIN AH23 [get_ports SPI_1_0_io1_io]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_1_0_sck_io]
set_property PACKAGE_PIN AJ24 [get_ports SPI_1_0_sck_io]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
