/* Generated by scripts/generate_dynamic_rate_descriptor.py; do not edit. */
#ifndef LASER_DYNAMIC_RATE_DESCRIPTOR_H
#define LASER_DYNAMIC_RATE_DESCRIPTOR_H

#include <stdint.h>

#define LASER_DYN_DESC_MAGIC UINT32_C(0x31505452)
#define LASER_DYN_DESC_VERSION 1U
#define LASER_DYN_DESC_WORDS 64U
#define LASER_DYN_DESC_MAX_MMCM_WRITES 16U
#define LASER_DYN_DESC_VERSION_COUNT \
+    ((LASER_DYN_DESC_WORDS << 16) | LASER_DYN_DESC_VERSION)
#define LASER_DYN_CRC32_INIT UINT32_C(0xFFFFFFFF)
#define LASER_DYN_CRC32_POLY UINT32_C(0xEDB88320)
#define LASER_DYN_CRC32_XOROUT UINT32_C(0xFFFFFFFF)

#define LASER_DYN_WORD_MAGIC 0x00U
#define LASER_DYN_WORD_VERSION_COUNT 0x01U
#define LASER_DYN_WORD_SEQUENCE 0x02U
#define LASER_DYN_WORD_CRC32 0x03U
#define LASER_DYN_WORD_FLAGS 0x04U
#define LASER_DYN_WORD_REQUESTED_RATE_LO 0x05U
#define LASER_DYN_WORD_REQUESTED_RATE_HI 0x06U
#define LASER_DYN_WORD_ACTUAL_RATE_LO 0x07U
#define LASER_DYN_WORD_ACTUAL_RATE_HI 0x08U
#define LASER_DYN_WORD_ERROR_PPM 0x09U
#define LASER_DYN_WORD_GT_PLL 0x0AU
#define LASER_DYN_WORD_GT_TXOUT 0x0BU
#define LASER_DYN_WORD_VERIFY_EXPECTED 0x0CU
#define LASER_DYN_WORD_VERIFY_TOLERANCE 0x0DU
#define LASER_DYN_WORD_MMCM_COUNT 0x0EU
#define LASER_DYN_WORD_RESERVED 0x0FU
#define LASER_DYN_WORD_MMCM_BASE 0x20U
#define LASER_DYN_WORD_STATUS_SEQUENCE 0x60U
#define LASER_DYN_WORD_STATUS_ERROR 0x61U
#define LASER_DYN_WORD_STATUS_PREVIOUS_GT 0x62U
#define LASER_DYN_WORD_STATUS_FINAL_GT 0x63U


static inline uint32_t laser_dyn_crc32_byte(uint32_t crc, uint8_t data)
{
    unsigned bit;
    crc ^= data;
    for (bit = 0U; bit < 8U; ++bit)
        crc = (crc & 1U) ? ((crc >> 1) ^ LASER_DYN_CRC32_POLY) : (crc >> 1);
    return crc;
}

static inline uint32_t laser_dyn_descriptor_crc32(const uint32_t *words)
{
    uint32_t crc = LASER_DYN_CRC32_INIT;
    unsigned i;
    unsigned byte_index;
    for (i = 0U; i < LASER_DYN_DESC_WORDS; ++i) {
        uint32_t word;
        if (i == LASER_DYN_WORD_CRC32)
            continue;
        word = words[i];
        for (byte_index = 0U; byte_index < 4U; ++byte_index) {
            crc = laser_dyn_crc32_byte(crc, (uint8_t)(word & 0xFFU));
            word >>= 8;
        }
    }
    return crc ^ LASER_DYN_CRC32_XOROUT;
}

#endif
