#ifndef LASER_HW_H
#define LASER_HW_H

#include "xparameters.h"

#define LASER_STRINGIFY_INNER(x) #x
#define LASmrdER_STRINGIFY(x) LASER_STRINGIFY_INNER(x)

#if defined(XPAR_AXI_GPIO_PARAM_CTRL_DEVICE_ID) && \
    defined(XPAR_AXI_GPIO_PARAM_CTRL_BASEADDR) && \
    defined(XPAR_AXI_GPIO_PARAM_CTRL_HIGHADDR)
#define LASER_GPIO_DEVICE_ID XPAR_AXI_GPIO_PARAM_CTRL_DEVICE_ID
#define LASER_GPIO_DEVICE_ID_NAME "XPAR_AXI_GPIO_PARAM_CTRL_DEVICE_ID"
#define LASER_GPIO_BASEADDR XPAR_AXI_GPIO_PARAM_CTRL_BASEADDR
#define LASER_GPIO_BASEADDR_NAME "XPAR_AXI_GPIO_PARAM_CTRL_BASEADDR"
#define LASER_GPIO_HIGHADDR XPAR_AXI_GPIO_PARAM_CTRL_HIGHADDR
#define LASER_GPIO_HIGHADDR_NAME "XPAR_AXI_GPIO_PARAM_CTRL_HIGHADDR"
#elif defined(XPAR_AXI_GPIO_0_DEVICE_ID) && \
      defined(XPAR_AXI_GPIO_0_BASEADDR) && \
      defined(XPAR_AXI_GPIO_0_HIGHADDR)
#define LASER_GPIO_DEVICE_ID XPAR_AXI_GPIO_0_DEVICE_ID
#define LASER_GPIO_DEVICE_ID_NAME "XPAR_AXI_GPIO_0_DEVICE_ID"
#define LASER_GPIO_BASEADDR XPAR_AXI_GPIO_0_BASEADDR
#define LASER_GPIO_BASEADDR_NAME "XPAR_AXI_GPIO_0_BASEADDR"
#define LASER_GPIO_HIGHADDR XPAR_AXI_GPIO_0_HIGHADDR
#define LASER_GPIO_HIGHADDR_NAME "XPAR_AXI_GPIO_0_HIGHADDR"
#elif defined(XPAR_GPIO_0_DEVICE_ID) && \
      defined(XPAR_GPIO_0_BASEADDR) && \
      defined(XPAR_GPIO_0_HIGHADDR)
#define LASER_GPIO_DEVICE_ID XPAR_GPIO_0_DEVICE_ID
#define LASER_GPIO_DEVICE_ID_NAME "XPAR_GPIO_0_DEVICE_ID"
#define LASER_GPIO_BASEADDR XPAR_GPIO_0_BASEADDR
#define LASER_GPIO_BASEADDR_NAME "XPAR_GPIO_0_BASEADDR"
#define LASER_GPIO_HIGHADDR XPAR_GPIO_0_HIGHADDR
#define LASER_GPIO_HIGHADDR_NAME "XPAR_GPIO_0_HIGHADDR"
#else
#error "AXI GPIO device ID macro was not generated. Check the Vitis BSP/xparameters.h."
#endif

#if defined(XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR) && \
    defined(XPAR_AXI_BRAM_CTRL_0_S_AXI_HIGHADDR)
#define LASER_BRAM_BASEADDR XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR
#define LASER_BRAM_BASEADDR_NAME "XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR"
#define LASER_BRAM_HIGHADDR XPAR_AXI_BRAM_CTRL_0_S_AXI_HIGHADDR
#define LASER_BRAM_HIGHADDR_NAME "XPAR_AXI_BRAM_CTRL_0_S_AXI_HIGHADDR"
#elif defined(XPAR_AXI_BRAM_CTRL_0_BASEADDR) && \
      defined(XPAR_AXI_BRAM_CTRL_0_HIGHADDR)
#define LASER_BRAM_BASEADDR XPAR_AXI_BRAM_CTRL_0_BASEADDR
#define LASER_BRAM_BASEADDR_NAME "XPAR_AXI_BRAM_CTRL_0_BASEADDR"
#define LASER_BRAM_HIGHADDR XPAR_AXI_BRAM_CTRL_0_HIGHADDR
#define LASER_BRAM_HIGHADDR_NAME "XPAR_AXI_BRAM_CTRL_0_HIGHADDR"
#elif defined(XPAR_BRAM_0_BASEADDR) && defined(XPAR_BRAM_0_HIGHADDR)
#define LASER_BRAM_BASEADDR XPAR_BRAM_0_BASEADDR
#define LASER_BRAM_BASEADDR_NAME "XPAR_BRAM_0_BASEADDR"
#define LASER_BRAM_HIGHADDR XPAR_BRAM_0_HIGHADDR
#define LASER_BRAM_HIGHADDR_NAME "XPAR_BRAM_0_HIGHADDR"
#else
#error "AXI BRAM Controller base-address macro was not generated."
#endif

#ifndef LASER_GPIO_BASEADDR
#error "AXI GPIO base/high-address macros were not generated."
#endif

#ifndef LASER_BRAM_HIGHADDR
#error "AXI BRAM Controller high-address macro was not generated."
#endif

#define LASER_GPIO_CTRL_CHANNEL   1U
#define LASER_GPIO_STATUS_CHANNEL 2U
#define LASER_GPIO_DATA_OFFSET    0x0U

#if defined(XPAR_AXI_GPIO_GT_STATUS_DEVICE_ID) && \
    defined(XPAR_AXI_GPIO_GT_STATUS_BASEADDR) && \
    defined(XPAR_AXI_GPIO_GT_STATUS_HIGHADDR)
#define LASER_GT_STATUS_GPIO_DEVICE_ID XPAR_AXI_GPIO_GT_STATUS_DEVICE_ID
#define LASER_GT_STATUS_GPIO_BASEADDR XPAR_AXI_GPIO_GT_STATUS_BASEADDR
#define LASER_GT_STATUS_GPIO_HIGHADDR XPAR_AXI_GPIO_GT_STATUS_HIGHADDR
#elif defined(XPAR_AXI_GPIO_1_DEVICE_ID) && defined(XPAR_AXI_GPIO_1_BASEADDR)
#define LASER_GT_STATUS_GPIO_DEVICE_ID XPAR_AXI_GPIO_1_DEVICE_ID
#define LASER_GT_STATUS_GPIO_BASEADDR XPAR_AXI_GPIO_1_BASEADDR
#define LASER_GT_STATUS_GPIO_HIGHADDR XPAR_AXI_GPIO_1_HIGHADDR
#else
#error "GT status AXI GPIO macro was not generated. Regenerate platform/BSP from laser_tx_board_top_gt_profile0.xsa."
#endif

#if defined(XPAR_AXI_GPIO_AD9528_MEASURE_DEVICE_ID) && \
    defined(XPAR_AXI_GPIO_AD9528_MEASURE_BASEADDR) && \
    defined(XPAR_AXI_GPIO_AD9528_MEASURE_HIGHADDR)
#define LASER_AD9528_MEASURE_GPIO_DEVICE_ID XPAR_AXI_GPIO_AD9528_MEASURE_DEVICE_ID
#define LASER_AD9528_MEASURE_GPIO_BASEADDR XPAR_AXI_GPIO_AD9528_MEASURE_BASEADDR
#define LASER_AD9528_MEASURE_GPIO_HIGHADDR XPAR_AXI_GPIO_AD9528_MEASURE_HIGHADDR
#else
#error "AD9528 measurement AXI GPIO macro was not generated. Regenerate platform/BSP from the latest XSA."
#endif
#if defined(XPAR_PS7_SPI_1_DEVICE_ID)
#define LASER_SPI_DEVICE_ID XPAR_PS7_SPI_1_DEVICE_ID
#elif defined(XPAR_XSPIPS_0_DEVICE_ID)
#define LASER_SPI_DEVICE_ID XPAR_XSPIPS_0_DEVICE_ID
#else
#error "PS SPI1 macro was not generated. Check the new XSA/BSP."
#endif

#define LASER_GT_STATUS_CHANNEL 1U
#define LASER_AD9528_SPI_SLAVE  1U

/* Runtime-rate hardware builds must use symbols generated from the matching
 * XSA.  Missing BSP symbols are a build error; silently falling back to a
 * hand-written address could pair firmware with an incompatible bitstream. */
#if defined(XPAR_AXI_GPIO_DYNAMIC_MAILBOX_BASEADDR)
#define LASER_DYNAMIC_MAILBOX_GPIO_BASEADDR \
    XPAR_AXI_GPIO_DYNAMIC_MAILBOX_BASEADDR
#else
#error "Dynamic mailbox AXI GPIO macro is missing. Regenerate BSP from the timing-clean XSA."
#endif

#if defined(XPAR_AXI_BRAM_DYN_DESC_S_AXI_BASEADDR)
#define LASER_DYNAMIC_DESCRIPTOR_BRAM_BASEADDR \
    XPAR_AXI_BRAM_DYN_DESC_S_AXI_BASEADDR
#elif defined(XPAR_AXI_BRAM_DYN_DESC_BASEADDR)
#define LASER_DYNAMIC_DESCRIPTOR_BRAM_BASEADDR \
    XPAR_AXI_BRAM_DYN_DESC_BASEADDR
#else
#error "Dynamic descriptor AXI BRAM macro is missing. Regenerate BSP from the timing-clean XSA."
#endif

#define LASER_CONFIG_STRIDE_BYTES 64U
#define LASER_CONFIG_WORD_COUNT   16U

#endif
