#!/usr/bin/env python3
"""Generate the shared C/Verilog dynamic-rate descriptor constants."""

from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]

SPEC = {
    "magic": 0x31505452,
    "version": 1,
    "descriptor_words": 64,
    "max_mmcm_writes": 16,
    "crc_word": 3,
    "status_base_word": 0x60,
    "words": {
        "MAGIC": 0x00, "VERSION_COUNT": 0x01, "SEQUENCE": 0x02,
        "CRC32": 0x03, "FLAGS": 0x04, "REQUESTED_RATE_LO": 0x05,
        "REQUESTED_RATE_HI": 0x06, "ACTUAL_RATE_LO": 0x07,
        "ACTUAL_RATE_HI": 0x08, "ERROR_PPM": 0x09, "GT_PLL": 0x0A,
        "GT_TXOUT": 0x0B, "VERIFY_EXPECTED": 0x0C,
        "VERIFY_TOLERANCE": 0x0D, "MMCM_COUNT": 0x0E,
        "RESERVED": 0x0F, "MMCM_BASE": 0x20,
        "STATUS_SEQUENCE": 0x60, "STATUS_ERROR": 0x61,
        "STATUS_PREVIOUS_GT": 0x62, "STATUS_FINAL_GT": 0x63,
    },
}


def banner() -> str:
    return "/* Generated by scripts/generate_dynamic_rate_descriptor.py; do not edit. */\n"


def generate_c() -> str:
    lines = [banner(), "#ifndef LASER_DYNAMIC_RATE_DESCRIPTOR_H\n",
             "#define LASER_DYNAMIC_RATE_DESCRIPTOR_H\n\n", "#include <stdint.h>\n\n"]
    lines += [
        f"#define LASER_DYN_DESC_MAGIC UINT32_C(0x{SPEC['magic']:08X})\n",
        f"#define LASER_DYN_DESC_VERSION {SPEC['version']}U\n",
        f"#define LASER_DYN_DESC_WORDS {SPEC['descriptor_words']}U\n",
        f"#define LASER_DYN_DESC_MAX_MMCM_WRITES {SPEC['max_mmcm_writes']}U\n",
        "#define LASER_DYN_DESC_VERSION_COUNT \\\n+    ((LASER_DYN_DESC_WORDS << 16) | LASER_DYN_DESC_VERSION)\n",
        "#define LASER_DYN_CRC32_INIT UINT32_C(0xFFFFFFFF)\n",
        "#define LASER_DYN_CRC32_POLY UINT32_C(0xEDB88320)\n",
        "#define LASER_DYN_CRC32_XOROUT UINT32_C(0xFFFFFFFF)\n\n",
    ]
    for name, value in SPEC["words"].items():
        lines.append(f"#define LASER_DYN_WORD_{name} 0x{value:02X}U\n")
    lines.append("""

static inline uint32_t laser_dyn_crc32_byte(uint32_t crc, uint8_t data)
{
    unsigned bit;
    crc ^= data;
    for (bit = 0U; bit < 8U; ++bit)
        crc = (crc & 1U) ? ((crc >> 1) ^ LASER_DYN_CRC32_POLY) : (crc >> 1);
    return crc;
}

static inline uint32_t laser_dyn_descriptor_crc32(const uint32_t *words)
{
    uint32_t crc = LASER_DYN_CRC32_INIT;
    unsigned i;
    unsigned byte_index;
    for (i = 0U; i < LASER_DYN_DESC_WORDS; ++i) {
        uint32_t word;
        if (i == LASER_DYN_WORD_CRC32)
            continue;
        word = words[i];
        for (byte_index = 0U; byte_index < 4U; ++byte_index) {
            crc = laser_dyn_crc32_byte(crc, (uint8_t)(word & 0xFFU));
            word >>= 8;
        }
    }
    return crc ^ LASER_DYN_CRC32_XOROUT;
}

#endif
""")
    return "".join(lines)


def generate_vh() -> str:
    lines = [banner(), "`ifndef LASER_DYNAMIC_RATE_DESCRIPTOR_VH\n",
             "`define LASER_DYNAMIC_RATE_DESCRIPTOR_VH\n\n",
             f"`define LASER_DYN_DESC_MAGIC 32'h{SPEC['magic']:08X}\n",
             f"`define LASER_DYN_DESC_VERSION 16'd{SPEC['version']}\n",
             f"`define LASER_DYN_DESC_WORDS 16'd{SPEC['descriptor_words']}\n",
             f"`define LASER_DYN_DESC_MAX_MMCM_WRITES 8'd{SPEC['max_mmcm_writes']}\n",
             "`define LASER_DYN_CRC32_INIT 32'hFFFFFFFF\n",
             "`define LASER_DYN_CRC32_POLY 32'hEDB88320\n",
             "`define LASER_DYN_CRC32_XOROUT 32'hFFFFFFFF\n\n"]
    for name, value in SPEC["words"].items():
        lines.append(f"`define LASER_DYN_WORD_{name} 8'h{value:02X}\n")
    lines.append("\n`endif\n")
    return "".join(lines)


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text(encoding="utf-8") != content:
        path.write_text(content, encoding="utf-8", newline="\n")


def main() -> None:
    write_if_changed(ROOT / "vitis_bringup/bringup/src/laser_dynamic_rate_descriptor.h", generate_c())
    write_if_changed(ROOT / "rtl/laser_dynamic_rate_descriptor.vh", generate_vh())
    write_if_changed(ROOT / "generated/dynamic_rate_descriptor_spec.json",
                     json.dumps(SPEC, indent=2, sort_keys=True) + "\n")


if __name__ == "__main__":
    main()
