# Validate system.bd and build the bitstream from the existing laser_tx project.
# Optional variables set before sourcing:
#   CLEAN_REBUILD = 1 (default) resets synth_1/impl_1 first.
#   EXPORT_XSA    = 1 (default) writes laser_tx.xsa including the bitstream.

if {![info exists CLEAN_REBUILD]} { set CLEAN_REBUILD 1 }
if {![info exists EXPORT_XSA]} { set EXPORT_XSA 1 }
if {![info exists VALIDATE_ONLY]} { set VALIDATE_ONLY 0 }

set script_dir [file dirname [file normalize [info script]]]
set project_dir [file dirname $script_dir]
set project_file [file join $project_dir laser_tx.xpr]

proc laser_build_fail {message} {
    puts stderr "ERROR: $message"
    return -code error $message
}

if {[llength [get_projects -quiet]] == 0} {
    if {![file exists $project_file]} { laser_build_fail "Project not found: $project_file" }
    open_project $project_file
}

set pin_xdc [file join $project_dir constraints laser_sync_pins_template.xdc]
if {[file exists $pin_xdc] && [llength [get_files -quiet $pin_xdc]] == 0} {
    add_files -fileset constrs_1 -norecurse $pin_xdc
}

set system_bd [get_files -quiet */system.bd]
if {[llength $system_bd] != 1} { laser_build_fail "Expected exactly one system.bd in the project." }
if {[llength [get_bd_designs -quiet system]] == 0} { open_bd_design $system_bd }
current_bd_design system

validate_bd_design
save_bd_design
generate_target all $system_bd

set wrapper_result [make_wrapper -files $system_bd -top]
set wrapper_candidates [list]
foreach candidate $wrapper_result {
    if {[file exists $candidate]} { lappend wrapper_candidates [file normalize $candidate] }
}
if {[llength $wrapper_candidates] == 0} {
    set conventional_wrapper [file join $project_dir laser_tx.gen sources_1 bd system hdl system_wrapper.v]
    if {[file exists $conventional_wrapper]} { lappend wrapper_candidates $conventional_wrapper }
}
if {[llength $wrapper_candidates] != 1} {
    laser_build_fail "Could not identify exactly one generated system_wrapper.v: $wrapper_candidates"
}
set wrapper_file [lindex $wrapper_candidates 0]
if {[llength [get_files -quiet $wrapper_file]] == 0} {
    add_files -fileset sources_1 -norecurse $wrapper_file
} else {
    puts "INFO: Wrapper already belongs to sources_1: $wrapper_file"
}
# system_wrapper is generated by the BD, but it is instantiated by the
# user-maintained board top.  Building system_wrapper directly would bypass
# the board-level SS2 tie-off and produce a bitstream with a different top.
set_property top laser_tx_board_top [get_filesets sources_1]
update_compile_order -fileset sources_1

if {[get_property top [current_fileset]] ne "laser_tx_board_top"} {
    laser_build_fail "sources_1 top must be laser_tx_board_top."
}

if {$VALIDATE_ONLY} {
    puts "INFO: VALIDATE_ONLY=1; BD validation, output products, and wrapper checks passed."
    return
}

if {$CLEAN_REBUILD} {
    if {[get_property PROGRESS [get_runs impl_1]] ne "0%"} { reset_run impl_1 }
    if {[get_property PROGRESS [get_runs synth_1]] ne "0%"} { reset_run synth_1 }
}

launch_runs synth_1 -jobs 8
wait_on_run synth_1
set synth_status [get_property STATUS [get_runs synth_1]]
if {![string match "*Complete*" $synth_status]} {
    laser_build_fail "Synthesis did not complete successfully: $synth_status"
}

launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1
set impl_status [get_property STATUS [get_runs impl_1]]
if {![string match "*Complete*" $impl_status]} {
    laser_build_fail "Implementation/bitstream did not complete successfully: $impl_status"
}

if {$EXPORT_XSA} {
    set xsa_file [file join $project_dir laser_tx.xsa]
    write_hw_platform -fixed -include_bit -force -file $xsa_file
    puts "INFO: Exported hardware platform: $xsa_file"
}
puts "INFO: Bitstream build completed successfully."
